/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: [
    '@tiptap/react',
    '@tiptap/starter-kit',
    '@tiptap/core',
    '@tiptap/extension-underline',
    '@tiptap/extension-highlight',
    '@tiptap/extension-text-align',
    '@tiptap/extension-link',
    '@tiptap/extension-image',
    '@tiptap/extension-placeholder',
    '@tiptap/pm',
  ],
  images: {
    unoptimized: false,
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'czjzizrzmqcdwgtxwuks.supabase.co',
        pathname: '/storage/v1/object/public/**',
      },
    ],
  },
  compress: true,
  poweredByHeader: false,
  trailingSlash: true,
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'X-Frame-Options',
            value: 'SAMEORIGIN',
          },
          {
            key: 'X-XSS-Protection',
            value: '1; mode=block',
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin',
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=(self), payment=()',
          },
          {
            key: 'Content-Security-Policy-Report-Only',
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com",
              "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
              "font-src 'self' https://fonts.gstatic.com",
              "img-src 'self' data: https:",
              "connect-src 'self' https://www.google-analytics.com",
              "frame-src 'self' https://www.youtube.com https://www.google.com",
              "report-uri /api/csp-report",
            ].join('; '),
          },
        ],
      },
    ]
  },
  async redirects() {
    return [
      // ── Existing fixes ────────────────────────────────────────────────────
      { source: '/nacc', destination: '/naac', permanent: true },
      { source: '/doctor-of-philosophy-phd', destination: '/phd', permanent: true },
      { source: '/excel', destination: '/', permanent: true },
      { source: '/b-pharmacylateral-entry', destination: '/b-pharmacy-lateral-entry', permanent: true },
      { source: '/blog/b-pharm-vs-pharm-d/', destination: '/', permanent: true },
      { source: '/about/', destination: '/overview/', permanent: true },
      { source: '/nirf-2024/', destination: '/nirf/nirf-2024/', permanent: true },
      { source: '/nirf-2025/', destination: '/nirf/nirf-2025/', permanent: true },

      // ── WordPress security blocks ─────────────────────────────────────────
      { source: '/wp-includes/:path*', destination: '/', permanent: true },
      { source: '/wp-admin/:path*', destination: '/', permanent: true },
      { source: '/wp-json/:path*', destination: '/', permanent: true },
      { source: '/xmlrpc.php', destination: '/', permanent: true },

      // ── PDF redirects (server-side) ───────────────────────────────────────
      { source: '/administration/', destination: '/pdf/administration.pdf', permanent: true },
      { source: '/animal-house/', destination: '/pdf/ANIMAL-HOUSE-FACILITY.pdf', permanent: true },
      { source: '/attainment-cos-pos/', destination: '/pdf/ATTAINMENT-OF-COs-AND-POs.pdf', permanent: true },
      { source: '/audit-statements-finance/', destination: '/pdf/Audit-Statements-Finance.pdf', permanent: true },
      { source: '/barrier-free-environment/', destination: '/pdf/DISABLED-FRIENDLY-AND-BARRIER-FREE-ENVIRONMENT.pdf', permanent: true },
      { source: '/circulars/', destination: '/pdf/CIRCULARS-AND-NOTICES.pdf', permanent: true },
      { source: '/cpio/', destination: '/pdf/Central-Public-Information-Officer.pdf', permanent: true },
      { source: '/feedback-analysis/', destination: '/pdf/Feedback-Analysis.pdf', permanent: true },
      { source: '/newsletters/', destination: '/pdf/NEWSLETTER.pdf', permanent: true },
      { source: '/sedg-cell/', destination: '/pdf/SOCIO-ECONOMICALLY-DISADVANTAGED-GROUP-CELL.pdf', permanent: true },
      { source: '/ugc-public-disclosure-compliance/', destination: '/pdf/UGC-PUBLIC-DISCLOSURE-COMPLIANCE-LETTER.pdf', permanent: true },
      { source: '/undertaking/', destination: '/pdf/UNDERTAKING.pdf', permanent: true },
      { source: '/various-committees/', destination: '/pdf/Various-Committees.pdf', permanent: true },

      // ── GROUP 1: Old WordPress PDF uploads → homepage ────────────────────
      { source: '/wp-content/:path*', destination: '/', permanent: true },

      // ── GROUP 2: Faculty profile pages → /faculty/ ───────────────────────
      { source: '/dr-alwin-simon-m/', destination: '/faculty/', permanent: true },
      { source: '/faculty/dr-k-lakshmi/', destination: '/faculty/', permanent: true },
      { source: '/faculty/dr-m-venkatesan/', destination: '/faculty/', permanent: true },
      { source: '/faculty/dr-s-shanmugam/', destination: '/faculty/', permanent: true },
      { source: '/faculty/dr-a-rajasekaran/', destination: '/faculty/', permanent: true },
      { source: '/faculty/dr-r-murugesan/', destination: '/faculty/', permanent: true },
      { source: '/dr-carolin-nimila/', destination: '/faculty/', permanent: true },
      { source: '/mrs-v-sevanthi/', destination: '/faculty/', permanent: true },
      { source: '/mr-v-venkateswaran/', destination: '/faculty/', permanent: true },
      { source: '/ms-s-divyadharshini/', destination: '/faculty/', permanent: true },
      { source: '/dr-s-ananda-thangadurai/', destination: '/faculty/', permanent: true },
      { source: '/ms-k-k-sneha/', destination: '/faculty/', permanent: true },
      { source: '/dr-aswin-sarath/', destination: '/faculty/', permanent: true },
      { source: '/ms-v-thenmozhi/', destination: '/faculty/', permanent: true },
      { source: '/mr-r-krishnan/', destination: '/faculty/', permanent: true },
      { source: '/dr-b-rajkapoor/', destination: '/faculty/', permanent: true },
      { source: '/dr-m-vijayabaskaran/', destination: '/faculty/', permanent: true },
      { source: '/dr-v-sekar/', destination: '/faculty/', permanent: true },
      { source: '/dr-v-senthil/', destination: '/faculty/', permanent: true },
      { source: '/dr-n-venkateswaramurthy/', destination: '/faculty/', permanent: true },
      { source: '/dr-k-v-uma/', destination: '/faculty/', permanent: true },
      { source: '/ms-n-mohanapriya/', destination: '/faculty/', permanent: true },

      // ── GROUP 3: Shopify / Apple / WooCommerce junk → homepage ───────────
      { source: '/cart', destination: '/', permanent: true },
      { source: '/cart/:path*', destination: '/', permanent: true },
      { source: '/pages/:path*', destination: '/', permanent: true },
      { source: '/account/:path*', destination: '/', permanent: true },
      { source: '/products/:path*', destination: '/', permanent: true },

      // ── GROUP 4: WordPress author / category / tag archives ───────────────
      { source: '/author/:path*', destination: '/blog/', permanent: true },
      { source: '/category/admission-zone/', destination: '/admissions/', permanent: true },
      { source: '/category/admission/', destination: '/admissions/', permanent: true },
      { source: '/category/:path*', destination: '/blog/', permanent: true },
      { source: '/tag/:path*', destination: '/blog/', permanent: true },

      // ── GROUP 5: WordPress index.php URLs ────────────────────────────────
      { source: '/index.php/b-pharm/', destination: '/b-pharmacy/', permanent: true },
      { source: '/index.php/m-pharmacy/', destination: '/m-pharmacy/', permanent: true },
      { source: '/index.php/pg-courses/', destination: '/m-pharmacy/', permanent: true },
      { source: '/index.php/ug-courses/', destination: '/b-pharmacy/', permanent: true },
      { source: '/index.php/ph-d-doctor-of-philosophy/', destination: '/phd/', permanent: true },
      { source: '/index.php/:path*', destination: '/:path*', permanent: true },
      { source: '/index.html', destination: '/', permanent: true },

      // ── GROUP 6: CO-PO curriculum pages → B.Pharm COs/POs ────────────────
      { source: '/pharmacology-1-theoryiv-sem-_/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/cellular-and-molecular-biology-co-_po/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/mpc-practical-i/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/spp-co-and-po/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/cosmectics-and-cosmecuticals/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-modern-pharmaceutical-analytical-techniques-2/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-modern-pharmaceutical-analytical-techniques/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/pharmacology-practical-i-co-_-po/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-pharm-analysis/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-and-po-iv-sem-cognosy-i/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/pharmacology-ii-co-po/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-remedial-biology/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/hdt-co-and-po/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-biochemistry/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/ait-co-po-iv-b-pharm/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-pharma-marketing/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-bppk/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-pic-i-semester/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/ima-co-po-iv-b-pharm/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/pharmacology-1-practicaliv-sem/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-b-pharm-ceutics-1-3/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/industrial-pharmacy-i/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-bppk-bp/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/bpharmmc-iii-co-po/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/pharmaceutical-microbiology/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/environmental-sciences-co-and-po/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/pharmacognosy-and-phytopharmaceuticals/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/physical-pharmaceutics-i-theorypractical/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/drug-delivery-system/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/pharmaceutical-engineering/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/pharmaceutical-formulations/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/co-po-pdd/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/pharmacognosy-ii-co-and-po/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/physical-pharmaceutics-i_ii-iii-_ivsem-theorypractical/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/pharmacognosy/', destination: '/bpharm-cos-pos/', permanent: true },
      { source: '/cnp-co/', destination: '/bpharm-cos-pos/', permanent: true },

      // ── GROUP 6 cont.: CO-PO curriculum pages → M.Pharm COs/POs ──────────
      { source: '/molecular-pharmaceutics/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/mpat-co-_po/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/co-po-advanced-pharmacology-ii/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/co-po-advanced-pharmaceutical-analysis/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/herbal-and-cosmetic-analysis-co-po-2-2/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/herbal-and-cosmetic-analysis-co-po/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/co-po-quality-control-and-quality-assurance/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/co-po-modern-bio-analytical-techniques/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/mpharm-aoc-i-co-po/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/mpharm-aoc-ii-co-po/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/co-po-m-pharm-practical-analysis-i/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/advanced-pharmacology-i-co-_-po/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/quality-assurance-co-po/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/co-po-ptsm-ii/', destination: '/mpharm-cos-pos/', permanent: true },
      { source: '/regulatory-affair/', destination: '/mpharm-cos-pos/', permanent: true },

      // ── GROUP 6 cont.: CO-PO curriculum pages → Pharm.D COs/POs ─────────
      { source: '/co-po-poc-iii-theory/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/clinical-research-co-po/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/cell-and-molecular-biology-co-_po-8th-sem/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/pharmacology-ii-practical-v-sem/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/biostat-co-po/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/co-po-pharm-analysis-iii-pharm-d/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/co-po-crpv/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/co-po-mc-ii/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/amc-1-sem/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/co-po-pharmacology-1-pharm-d/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/pharm-d-mc-co-po/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/co-po-hap-2/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/pathophysiology-ii-sem/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/clinical-pharmacokinetics-couse-outcome-with-mapping/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/co-po-poc-i-theory-and-practical/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/community-pharmacy-co-and-po/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/mpc-practical-ii/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/pharmacology-iii-co-po/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/co-po-pharmacology-ii-sem-practical/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/pharmacotherapeutics-iii-co-po/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/pic-1-pharm-d/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/pharmacotherapeutics-i/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/pharmacotherapeutics-ii/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/screening-and-toxicology-i-co-_po/', destination: '/pharmd-cos-pos/', permanent: true },
      { source: '/clinical-pharmacy-co-po_/', destination: '/pharmd-cos-pos/', permanent: true },

      // ── GROUP 7: Old programme pages → new programme pages ───────────────
      { source: '/bachelor-of-pharmacy/', destination: '/b-pharmacy/', permanent: true },
      { source: '/b-pharm/', destination: '/b-pharmacy/', permanent: true },
      { source: '/ug-courses/', destination: '/b-pharmacy/', permanent: true },
      { source: '/programmes/', destination: '/b-pharmacy/', permanent: true },
      { source: '/programmes', destination: '/b-pharmacy/', permanent: true },
      { source: '/master-of-pharmacy-2/', destination: '/m-pharmacy/', permanent: true },
      { source: '/m-pharm/', destination: '/m-pharmacy/', permanent: true },
      { source: '/pg-courses/', destination: '/m-pharmacy/', permanent: true },
      { source: '/pharm-d-doctor-of-pharmacy/', destination: '/pharm-d/', permanent: true },
      { source: '/pham-d/', destination: '/pharm-d/', permanent: true },
      { source: '/pharm-dpost-baccalaureate/', destination: '/pharm-d/', permanent: true },
      { source: '/pharm-d-post-baccalaureate/', destination: '/pharm-d/', permanent: true },
      { source: '/pharm-d-post-baccalaureate-2/', destination: '/pharm-d/', permanent: true },
      { source: '/pharm-pb/', destination: '/pharm-d/', permanent: true },
      { source: '/ph-d/', destination: '/phd/', permanent: true },
      { source: '/ph-d-doctor-of-philosophy/', destination: '/phd/', permanent: true },
      { source: '/doctor-of-philosophy-ph-d/', destination: '/phd/', permanent: true },
      { source: '/research-courses/', destination: '/phd/', permanent: true },

      // ── GROUP 8: Department pages → new department pages ─────────────────
      { source: '/department-of-pharmacology/', destination: '/pharmacology/', permanent: true },
      { source: '/department-of-pharmacy-practice/', destination: '/pharmacy-practice/', permanent: true },
      { source: '/department-of-pharmaceutics/', destination: '/pharmaceutics/', permanent: true },
      { source: '/deparment-of-pharmaceutical-analysis/', destination: '/pharmaceutical-analysis/', permanent: true },

      // ── GROUP 9: Old blog / event posts ──────────────────────────────────
      { source: '/world-kidney-day/', destination: '/blog/', permanent: true },
      { source: '/world-hepatitis-day/', destination: '/blog/', permanent: true },
      { source: '/blood-donation-camp-2/', destination: '/blog/', permanent: true },
      { source: '/blood-donation-camp/', destination: '/blog/', permanent: true },
      { source: '/pharmacy-week/', destination: '/blog/', permanent: true },
      { source: '/hands-on-workshops-exploring-career-pathways-entrepreneurial-insights-and-clinical-interventions/', destination: '/blog/', permanent: true },
      { source: '/internship-opportunities-for-students/', destination: '/internship-opportunities/', permanent: true },
      { source: '/the-nss-special-camp-at-kolli-hills/', destination: '/nss/', permanent: true },
      { source: '/apti-national-level-conference/', destination: '/blog/', permanent: true },
      { source: '/digital-and-brand-ambassadors-dba-graduation-day-2024/', destination: '/blog/', permanent: true },
      { source: '/dba-batch-2-inauguration-day-2025/', destination: '/blog/', permanent: true },
      { source: '/yugha-2024-3rd-edition-cultural-event-hosted-by-vet-institute-of-arts-and-science-erode/', destination: '/blog/', permanent: true },
      { source: '/iic-7-0-self-driven-activity-design-and-development-of-medtech-products/', destination: '/institutions-innovation-council/', permanent: true },
      { source: '/mastering-essential-skills-for-pharmacy-student-success/', destination: '/blog/', permanent: true },
      { source: '/kumarapalayam-bypass-marathon/', destination: '/blog/', permanent: true },
      { source: '/awarness-program-on-niral-thiruvizha/', destination: '/blog/', permanent: true },
      { source: '/international-level-one-day-cep-program-28-07-2023/', destination: '/blog/', permanent: true },
      { source: '/common-mistakes-made-by-pharmacy-students/', destination: '/blog/', permanent: true },
      { source: '/alumni-insight-programme/', destination: '/alumni/', permanent: true },
      { source: '/intra-institutional-business-plan-competition/', destination: '/edc/', permanent: true },
      { source: '/national-service-scheme-1/', destination: '/nss/', permanent: true },
      { source: '/one-day-international-level-continuing-education-programme-cep/', destination: '/blog/', permanent: true },
      { source: '/national-innovation-and-startup-policy-2020-2021/', destination: '/national-innovation-startup-policy/', permanent: true },
      { source: '/jkk-nattraja-college-of-pharmacy-on-behalf-of-98th-founders-day-melodious-solo-song-competition/', destination: '/blog/', permanent: true },
      { source: '/best-poster-award/', destination: '/blog/', permanent: true },
      { source: '/exciting-collaboration-alert/', destination: '/blog/', permanent: true },
      { source: '/62nd-national-pharmacy-week-sports/', destination: '/blog/', permanent: true },
      { source: '/celebrating-the-98th-birthday-of-jkk-nattaraja-sir-founders-day-at-jkk-nattaraja-college-of-pharmacy/', destination: '/blog/', permanent: true },
      { source: '/innovating-research-with-artificial-intelligence-a-comprehensive-workshop-on-efficiently-constructing-a-research-paper-on-international-standards-with-cutting-edge-ai-tools-3/', destination: '/blog/', permanent: true },
      { source: '/driven-by-innovation-solution-experience-leveraging-market-analysis-for-successful-entrepreneurship/', destination: '/blog/', permanent: true },
      { source: '/a-bright-future-in-pharmacists-the-impact-of-a-degree-from-jkkn-college-of-pharmacy/', destination: '/blog/', permanent: true },
      { source: '/jkkn-college-of-pharmacy-offers-bachelor-of-pharmacy-b-pharm-and-master-of-pharmacy-m-pharm-programs-in-various-specializations/', destination: '/blog/', permanent: true },
      { source: '/jkkn-admissions-open-apply-now/', destination: '/admissions/', permanent: true },
      { source: '/the-role-of-the-pharmacist-in-cardiology/', destination: '/blog/', permanent: true },
      { source: '/the-quality-of-education-and-facilities-at-jkkn-college-of-pharmacy/', destination: '/blog/', permanent: true },

      // ── GROUP 10: Old college info / admin pages ──────────────────────────
      { source: '/faculty-detail/', destination: '/faculty/', permanent: true },
      { source: '/governance-leadership-and-management/', destination: '/overview/', permanent: true },
      { source: '/about/affiliation-details/university/', destination: '/university/', permanent: true },
      { source: '/about/affiliation-details/', destination: '/affiliation-details/', permanent: true },
      { source: '/placement/', destination: '/placements/', permanent: true },
      { source: '/placement', destination: '/placements/', permanent: true },
      { source: '/placement-cell-and-its-activities/', destination: '/placement-cell/', permanent: true },
      { source: '/admission-process/', destination: '/admissions/', permanent: true },
      { source: '/admission-process', destination: '/admissions/', permanent: true },
      { source: '/admission-procedure/', destination: '/admissions/', permanent: true },
      { source: '/admission/jkkn-admissions-open-apply-now/', destination: '/admissions/', permanent: true },
      { source: '/student-support-and-progression/', destination: '/admissions/', permanent: true },
      { source: '/student-support-cell/', destination: '/admissions/', permanent: true },
      { source: '/about-us-overview/', destination: '/overview/', permanent: true },
      { source: '/equal-opportunity-cell-eoc/', destination: '/equal-opportunity-cell/', permanent: true },
      { source: '/alumini-committee/', destination: '/alumni/', permanent: true },
      { source: '/alumni-network-and-contributions/', destination: '/alumni/', permanent: true },
      { source: '/sports-gallery/', destination: '/gallery/', permanent: true },
      { source: '/classroom-gallery/', destination: '/gallery/', permanent: true },
      { source: '/academic-year-2018-2019/', destination: '/blog/', permanent: true },
      { source: '/academic-year-2015-2016/', destination: '/blog/', permanent: true },
      { source: '/academic-year-2016-2017/', destination: '/blog/', permanent: true },
      { source: '/time-table/', destination: '/bpharm-time-table/', permanent: true },
      { source: '/academic-calendar/', destination: '/exam-schedule/', permanent: true },
      { source: '/competitive-examination-and-carrier-2/', destination: '/competitive-examination/', permanent: true },
      { source: '/competitive-examination-and-carrier/', destination: '/competitive-examination/', permanent: true },
      { source: '/general-grievances/', destination: '/student-grievance-redressal-committee/', permanent: true },
      { source: '/grievances-redressal-committee/', destination: '/student-grievance-redressal-committee/', permanent: true },
      { source: '/generalrules-and-regulations/', destination: '/general-rules/', permanent: true },
      { source: '/ordinances-pertaining-to-examinations/', destination: '/ordinances/', permanent: true },
      { source: '/recognition-approval-accrediation/', destination: '/recognition-approval-and-accreditation/', permanent: true },
      { source: '/research-committee/', destination: '/research/', permanent: true },
      { source: '/cultural-commitee/', destination: '/cultural-committee/', permanent: true },
      { source: '/hostel-facilities/', destination: '/hostel/', permanent: true },
      { source: '/other-facility/', destination: '/central-facilities/', permanent: true },
      { source: '/auditorium/', destination: '/central-facilities/', permanent: true },
      { source: '/cad/', destination: '/central-facilities/', permanent: true },
      { source: '/campus/', destination: '/overview/', permanent: true },
      { source: '/present-information-about-the-library/', destination: '/library/', permanent: true },
      { source: '/industry-visit/', destination: '/internship-opportunities/', permanent: true },
      { source: '/payment-of-fees/', destination: '/fee-structure/', permanent: true },
      { source: '/outlook/', destination: '/digital-campus/', permanent: true },
      { source: '/work-space/', destination: '/digital-campus/', permanent: true },
      { source: '/digital/', destination: '/digital-campus/', permanent: true },
      { source: '/attendance/', destination: '/study-material/', permanent: true },
      { source: '/national-level-seminar/', destination: '/blog/', permanent: true },
      { source: '/latest-buzz/national-level-seminar/', destination: '/blog/', permanent: true },
      { source: '/past-events/intellectual-property-rights-day/', destination: '/blog/', permanent: true },
      { source: '/intellectual-property-rights-day/', destination: '/blog/', permanent: true },
      { source: '/explore-our-featured-links/', destination: '/', permanent: true },
      { source: '/web-stories/classroom/', destination: '/gallery/', permanent: true },
      { source: '/web-stories/online-journals/', destination: '/library/', permanent: true },
      { source: '/web-stories/every-pharmacy-student-needs-to-succeed-2/', destination: '/blog/', permanent: true },
      { source: '/web-stories/want-to-study-medical-courses/', destination: '/admissions/', permanent: true },
      { source: '/web-stories/placement-day-celebration-2025-a-grand-success-2/', destination: '/placements/', permanent: true },

      // ── GROUP 11: Junk / broken URLs ─────────────────────────────────────
      { source: '/8029-2/', destination: '/', permanent: true },
      { source: '/7576-2/', destination: '/', permanent: true },
      { source: '/8686-2/', destination: '/', permanent: true },
      { source: '/8647-2/', destination: '/', permanent: true },
      { source: '/testrh/', destination: '/', permanent: true },
      { source: '/trial/', destination: '/', permanent: true },

      // P0-5: Redirect duplicate NIRF root routes to canonical /nirf/ hierarchy
      { source: '/nirf-2024/', destination: '/nirf/nirf-2024/', permanent: true },
      { source: '/nirf-2025/', destination: '/nirf/nirf-2025/', permanent: true },
      // P3-3: Add /about/ redirect to /overview/
      { source: '/about/', destination: '/overview/', permanent: true },
      // Deleted blog post — redirect to homepage
      { source: '/blog/b-pharm-vs-pharm-d/', destination: '/', permanent: true },
      // Old URL with `&` + typo `accrediation` → canonical clean URL
      { source: '/recognition-approval-&-accrediation/', destination: '/recognition-approval-and-accreditation/', permanent: true },
    ]
  },
}

module.exports = nextConfig
